#!/usr/bin/expect

set login "admin"
#set addr "10.1.10.253"
#set addr "10.1.10.219"
set addr "10.1.10.236"
set pw "komprise123"

spawn ssh $login@$addr
expect "$login@$addr\'s password:"
send "$pw\r"
expect "#"
interact
